import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.162.0/build/three.module.js";
import {OrbitControls} from "https://cdn.jsdelivr.net/npm/three@0.162.0/examples/jsm/controls/OrbitControls.js";
const canvas=document.querySelector("#scene");const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xe8e1ff,.035);
const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);camera.position.set(0,0,7);
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=10;controls.autoRotate=true;controls.autoRotateSpeed=.55;
scene.add(new THREE.AmbientLight(0xffffff,1.8));
const lights=[[0xff3d9a,40,3,3,4],[0x16d9ff,35,-4,-2,3],[0x7c4dff,35,2,-4,-3],[0xffd84d,25,-2,4,-2]];
lights.forEach(([c,i,x,y,z])=>{const l=new THREE.PointLight(c,i,18);l.position.set(x,y,z);scene.add(l)});
const core=new THREE.Group();scene.add(core);
const geo=new THREE.IcosahedronGeometry(1.45,3);const mat=new THREE.MeshPhysicalMaterial({color:0xffffff,metalness:.65,roughness:.12,clearcoat:1,clearcoatRoughness:.08,emissive:0x5d36ff,emissiveIntensity:.18});const mesh=new THREE.Mesh(geo,mat);core.add(mesh);
const ringColors=[0xff3d9a,0x16d9ff,0x7c4dff,0xffd84d,0x36e38b];
ringColors.forEach((c,i)=>{const r=new THREE.Mesh(new THREE.TorusGeometry(1.9+i*.28,.014,10,180),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.72}));r.rotation.set(i*.55,i*.8,i*.35);core.add(r)});
const particlesGeo=new THREE.BufferGeometry(),count=2200,positions=new Float32Array(count*3),cols=new Float32Array(count*3);const palette=[new THREE.Color(0xff3d9a),new THREE.Color(0x16d9ff),new THREE.Color(0x7c4dff),new THREE.Color(0xffd84d),new THREE.Color(0x36e38b)];
for(let i=0;i<count;i++){const radius=THREE.MathUtils.randFloat(4,12),a=Math.random()*Math.PI*2,b=Math.acos(THREE.MathUtils.randFloatSpread(2)),j=i*3;positions[j]=radius*Math.sin(b)*Math.cos(a);positions[j+1]=radius*Math.cos(b);positions[j+2]=radius*Math.sin(b)*Math.sin(a);const c=palette[i%palette.length];cols[j]=c.r;cols[j+1]=c.g;cols[j+2]=c.b}
particlesGeo.setAttribute("position",new THREE.BufferAttribute(positions,3));particlesGeo.setAttribute("color",new THREE.BufferAttribute(cols,3));
const particles=new THREE.Points(particlesGeo,new THREE.PointsMaterial({size:.026,vertexColors:true,transparent:true,opacity:.72}));scene.add(particles);
let targetY=0;addEventListener("scroll",()=>targetY=scrollY/innerHeight);addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function animate(t){requestAnimationFrame(animate);core.rotation.y+=.0025;core.rotation.x+=.0008;particles.rotation.y=t*.00002;const s=Math.sin(t*.001)*.08;core.position.y+=(s-targetY*.22-core.position.y)*.025;camera.position.y+=(targetY*.15-camera.position.y)*.025;controls.update();renderer.render(scene,camera)}animate(0);
window.addEventListener("load",()=>setTimeout(()=>{const l=document.querySelector("#loader");l.style.opacity="0";l.style.visibility="hidden"},700));